### PR TITLE
Fix PHP 8.1 deprecation

### PR DESCRIPTION
**Pull request by ruudk**
On PHP 8.1 passing `null` to `strtolower` will produce this log:
```
strtolower(): Passing null to parameter #1 ($string) of type string is deprecated
```

I ran the whole test suite on PHP 8.1 and this was the only issue.

### CODE REVIEW

**Comment by ruudk** [comment]
@pamil What do you think of this? It seems to solve the PHP 8.1 deprecation on my CI pipeline. Is there anything you would want me to change/add/improve? Thanks

**Comment by Yozhef** [comment]
@ruudk fix in pr https://github.com/FriendsOfBehat/Mink/pull/5

**Comment by ruudk** [comment]
Thanks @Yozhef, when will it be tagged? 🙏

**Comment by Yozhef** [comment]
@ruudk new tag already releases v1.10.0

**Pull request closed without merging**
